name: Terraform CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4

      - name: Initialize Terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init

      - name: Format Terraform code
        run: terraform fmt -check

      - name: Validate Terraform configuration
        run: terraform validate

      # - name: Run Terraform Plan
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: eu-west-1
      #     TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
      #     TF_VAR_lakehouse_bucket_name: ${{ secrets.TF_VAR_LAKEHOUSE_BUCKET_NAME }}
      #     TF_VAR_shopware_glue_bucket_name: ${{ secrets.TF_VAR_SHOPWARE_GLUE_BUCKET_NAME }}
      #     TF_VAR_ingestion_bucket_name: ${{ secrets.TF_VAR_INGESTION_BUCKET_NAME }}
      #     TF_VAR_sfns_stream_arn: ${{ secrets.TF_VAR_SFNS_STREAM_ARN }}
      #     TF_VAR_sfns_daily_arn: ${{ secrets.TF_VAR_SFNS_DAILY_ARN }}
      #   run: terraform plan -input=false -out=terraform.tfplan

      - name: Show Terraform Plan
        run: terraform show terraform.tfplan
